version: '3'
services:

  redis:
    image: redis:7.0.5
    volumes:
      - ./config/redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

  postgres:
    image: postgres:13.0-alpine
    volumes:
    - ./config/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    - ./postgresql/data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:1.23.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - flask
    ports:
      - "80:80"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  flask:
    build: .
    environment:
      REDIS_HOST: redis
      ELASTIC_HOST: elastic
      CACHE_EXPIRE_IN_SECONDS: 300
      URL_HOST: 'flask'
    expose:
      - '5000'
    depends_on:
      - redis
      - postgres
      - jaeger
    command: >
      bash -c "flask db upgrade
      && python3 -m flask run --host=0.0.0.0 --port=5000"